resource_types:
- name: git-branch-heads
  type: docker-image
  source: {repository: vito/git-branch-heads-resource}

resources:
- name: flight-school
  type: git-branch-heads
  source:
    uri: https://github.com/nimerritt/flight-school

jobs:
- name: test-app
  plan:
  - get: flight-school
    trigger: true
  - task: tests
    file: flight-school/ci/build.yml
    version: every
